name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - run: go version
      - run: go build -v ./...
      - run: go test -v ./...
      - run: go vet ./...
      - run: go mod verify
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
           go-version-file: go.mod
           go-package: ./...
      - name: Install Cypress
        run: npm install cypress@13.7.3
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: go run .
          cache-key: somevalue
          wait-on: 'http://localhost:8080'
          install: false
        env:
          SERVER_ENV: test
          CYPRESS_CRASH_REPORTS: 0
          CYPRESS_COMMERCIAL_RECOMMENDATIONS: 0
