name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - run: go version
      - run: go build -v ./...
      - run: go test -v ./...
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: SERVER_ENV=test go run .
          cache-key: somevalue
          wait-on: 'http://localhost:3000'
        env:
          CYPRESS_CRASH_REPORTS: 0
          CYPRESS_COMMERCIAL_RECOMMENDATIONS: 0
